
services:
  - type: web
    name: kraken-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 3 -b 0.0.0.0:10000 app:app
    envVars:
      - key: KRAKEN_KEY
        sync: false
      - key: KRAKEN_SECRET
        sync: false
      - key: SHARED_SECRET
        sync: false
